
import Navbar from '@/components/navbar/page'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/page'
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Haseeb ul Hasan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
