import Navbar from "@/components/navbar/page";
import "./globals.css";
import Footer from "@/components/footer/page";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Haseeb ul Hasan",
  description: "Generated by create next app",
  icon: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
